"""run counters and node fields

Revision ID: 0003
Revises: 0002
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import postgresql

revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('run_nodes', sa.Column('iteration', sa.Integer(), server_default='0', nullable=False))
    op.add_column('run_nodes', sa.Column('feedback', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('run_nodes', sa.Column('model_override', sa.String(length=200), nullable=True))
    op.add_column('run_nodes', sa.Column('blocked_reason', sa.String(length=40), nullable=True))
    op.add_column('run_nodes', sa.Column('reused_from_run', sa.UUID(), nullable=True))
    op.add_column('runs', sa.Column('budget_tokens', sa.BigInteger(), nullable=True))
    op.add_column('runs', sa.Column('spent_tokens', sa.BigInteger(), server_default='0', nullable=False))
    op.add_column('runs', sa.Column('reserved_usd', sa.Numeric(precision=12, scale=6), server_default='0', nullable=False))
    op.add_column('runs', sa.Column('reserved_tokens', sa.BigInteger(), server_default='0', nullable=False))
    op.add_column('workflows', sa.Column('template_key', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflows', 'template_key')
    op.drop_column('runs', 'reserved_tokens')
    op.drop_column('runs', 'reserved_usd')
    op.drop_column('runs', 'spent_tokens')
    op.drop_column('runs', 'budget_tokens')
    op.drop_column('run_nodes', 'reused_from_run')
    op.drop_column('run_nodes', 'blocked_reason')
    op.drop_column('run_nodes', 'model_override')
    op.drop_column('run_nodes', 'feedback')
    op.drop_column('run_nodes', 'iteration')
    # ### end Alembic commands ###
